# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
include:
  - template: Security/SAST.gitlab-ci.yml
  - template: Security/Secret-Detection.gitlab-ci.yml

stages:
  - CI
  - CD
  - test

secret_detection:
  stage: CI
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_COMMIT_BRANCH == 'main'

nodejs-scan-sast: 
  stage: CI
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_COMMIT_BRANCH == 'main'

semgrep-sast:
  stage: CI
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_COMMIT_BRANCH == 'main'     


validate-app: 
  stage: CI
  image: python:latest
  script:
    - apt update -y
    - apt install nodejs -y 
    - apt install npm -y
    - curl -fsSL https://aka.ms/install-azd.sh | bash
    - azd package -e test --no-prompt
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_COMMIT_BRANCH == 'main'

lint:
  stage: CI
  image: node:14-alpine
  script:
    - pwd
    - npx prettier --write /builds/dnb/platypus/tmt/app/frontend
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_COMMIT_BRANCH == 'main'

validate-infra: 
  stage: CI
  image: 364737385840.dkr.ecr.eu-west-1.amazonaws.com/tools-azure-cli-python:1.0
  script: 
    - az config set bicep.use_binary_from_path=false
    - az bicep install
    - source infra/platypus-dev.env
    - echo $AZURE_DEPLOY_CLIENT_ID, $AZURE_DEPLOY_CLIENT_SECRET, $DNB_AZURE_TENANT_ID
    - az login --service-principal -u $AZURE_DEPLOY_CLIENT_ID -p $AZURE_DEPLOY_CLIENT_SECRET --tenant $DNB_AZURE_TENANT_ID
    - az deployment sub what-if --location westeurope --template-file infra/main.bicep --parameters @infra/cicd.parameters.json
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_COMMIT_BRANCH == 'main' 

deploy:
  stage: CD
  image: python:latest
  script:
    - apt update -y
    - apt install nodejs -y 
    - apt install npm -y
    - curl -fsSL https://aka.ms/install-azd.sh | bash
    - azd auth login --client-id $AZURE_DEPLOY_CLIENT_ID --tenant-id $DNB_AZURE_TENANT_ID --client-secret $AZURE_DEPLOY_CLIENT_SECRET
    # - az login --service-principal -u $AZURE_DEPLOY_CLIENT_ID -p $AZURE_DEPLOY_CLIENT_SECRET --tenant $DNB_AZURE_TENANT_ID
    - source infra/platypus-dev.env
    - azd env new cicd -l westeurope --subscription 564df8bf-50ab-4917-8082-b363158428c2
    - azd up -e cicd --no-prompt  
  rules:
    - if: $CI_COMMIT_BRANCH == 'main' && $CI_PIPELINE_SOURCE == 'push'
