  alex/EP-5629-CI-pipeline[m
  herman/EP-5624/FrontendStyling[m
  herman/EP-5654/DNBlogo[m
  herman/EP-5664/Data-cleanse[m
  herman/EP-5667/Aboutpage[m
  herman/EP-5683/retrieve-then-read[m
  herman/EP-5687/questionAfterSending[m
* [32mmain[m
  [31mremotes/origin/HEAD[m -> origin/main
  [31mremotes/origin/alex/EP-5629-CI-pipeline[m
  [31mremotes/origin/alex/EP-5654/compatible-dnb-logo[m
  [31mremotes/origin/alex/EP-5665/modify-approaches[m
  [31mremotes/origin/change-default-search-service-tier[m
  [31mremotes/origin/changeSearchTier[m
  [31mremotes/origin/hauk/EP-5631/infra-dryrun[m
  [31mremotes/origin/hauk/EP-5671/fix-dying-website[m
  [31mremotes/origin/hauk/EP-5681/edit-read-decompose[m
  [31mremotes/origin/hauk/codeowners[m
  [31mremotes/origin/herman/EP-5624/FrontendStyling[m
  [31mremotes/origin/herman/EP-5654/DNBlogo[m
  [31mremotes/origin/herman/EP-5664/Data-cleanse[m
  [31mremotes/origin/herman/EP-5667/Aboutpage[m
  [31mremotes/origin/herman/EP-5683/retrieve-then-read[m
  [31mremotes/origin/herman/EP-5687/questionAfterSending[m
  [31mremotes/origin/main[m
  [31mremotes/origin/njal/EP-5639/web2pdf[m
  [31mremotes/origin/njal/EP-5640/page-citation[m
  [31mremotes/origin/njal/EP-5669/show-answer-generation-information[m
  [31mremotes/origin/njal/bug/remove-wrong-prompt[m
